### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iShift** [digital-dreamer/twister-proxy#2]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Object.<anonymous> (/Users/Shift/twister-proxy/twister-proxy.js:201:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by digital-dreamer** [comment]
I see ... this is a common issue in node.js: because of security concerns, a process without root privileges is not allowed listen on ports lower that 1024, so it cannot access HTTP (80) or HTTPS (443) ports. There are two possible solutions:

Solution 1: run node with root privileges, like `sudo node twister-proxy.js &`

Or, if you are on a computer where you don't have root access, edit settings.json, and put a number bigger than 1024 but smaller than 65535 in "http_port".

We should put this in the readme, I didn't notice it when I wrote the proxy. More info about this issue: https://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports

BTW it is great that you are interested in this public servers idea. We kinda left it unfinished last April - the twister-core has support for public_server_mode, but the twister-html counterpart was not merged yet, it is this pull request: https://github.com/miguelfreitas/twister-html/pull/135 - if you would like to play with this a little bit, I can resolve the conflicts so that Miguel can merge it.

**Comment by iShift** [comment]
ok, i try it in future. 

Fix for readme https://github.com/digital-dreamer/twister-proxy/issues/2#issuecomment-69032528

It would be better if i can see normal error not exception and nodejs crash with ports < 1024
