### ISSUE TITLE
401 Unauthorized.

### ISSUE THREAD

**Issue by iShift** [digital-dreamer/twister-proxy#4]
I get 401 Unauthorized. 

Twister.conf:
rpcuser=user
rpcpassword=pwd
rpcallowip=127.0.0.1
daemon=1

twister-proxy conf: 
 "RPC": 
    { 
	"host": "127.0.0.1",
	"port": 28332,
	"user": "user",
	"password": "pwd"
    },

**Comment by digital-dreamer** [comment]
Yep, that is a bug - missing auth header. Authentication (user:password) was hardcoded in twister-html at the time a wrote this, so I didn't spot it. Since the, twister has moved to real authentication.

Now we need to get the UI part of public server mode ready to merge into twister-html. It works without that, but not the right way - it will try to make forbidden api calls, which the proxy blocks and records in the log. Also, the user interface should look different in public server mode - instead of asking you to log in, it will tell you to download twister to participate actively on the network. There is page with download link for twister, and some other parts of the UI are removed. It is done, but twister-html has since changed, and there are conflicts that need to be resolved. I think I will have time to work on it this weekend.

Thank you for catching the bugs :-)
